name: Run test case

on:
    push:
    pull_request:
    release:
        types:
            - published
            - prereleased

jobs:

    run_test_case:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                container:
                    - "emqx/build-env:erl23.2.7.2-emqx-2-ubuntu20.04"
                    - "emqx/build-env:erl24.0.1-emqx-1-ubuntu20.04"

        container: ${{ matrix.container }}
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Run tests
          run: |
            set -e
            make eunit
            make ct
            make cover
            # @TODO rebar3 tar does not include appup of dep apps
            # make relup-test
        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs
        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover
