name: Run test case

on:
    push:
    pull_request:
    release:
        types:
            - published
            - prereleased

jobs:

    run_test_case:

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                docker_image:
                  - "ghcr.io/emqx/emqx-builder/5.0-26:1.13.4-24.3.4.2-1-ubuntu20.04"
                  - "ghcr.io/emqx/emqx-builder/5.1-4:1.14.5-25.3.2-2-ubuntu20.04"
                  - "public.ecr.aws/docker/library/erlang:26"

        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: work around https://github.com/actions/checkout/issues/766
          run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        - name: Run tests
          env:
            DOCKER_IMAGE: "${{ matrix.docker_image }}"
          shell: bash
          run: |
            set -e
            docker build -t testimage --build-arg BUILD_FROM=${DOCKER_IMAGE} -f Dockerfile.test .
            docker network create --ipv6 --subnet 2001:0DB8::/112 testnet
            # TODO: stable QUIC tests in OTP 26
            if [[ "${DOCKER_IMAGE}" == *erlang:26* ]]; then
              docker run -d --net testnet --name testcontainer -e BUILD_WITHOUT_QUIC=1 testimage bash -c "tail -f /dev/null"
            else
              docker run -d --net testnet --name testcontainer testimage bash -c "tail -f /dev/null"
            fi
            docker exec testcontainer bash -c 'make eunit'
            docker exec testcontainer bash -c 'make ct'
            docker exec testcontainer bash -c 'make cover'
            # @TODO rebar3 tar does not include appup of dep apps
            # docker exec testcontainer bash -c 'make relup-test'
            # copy the build dir to host working dir for following build steps
            docker cp testcontainer:/_w/_build .
            docker rm -f testcontainer
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: logs
            path: _build/test/logs
        - uses: actions/upload-artifact@v3
          with:
            name: cover
            path: _build/test/cover
